name: Reusable workflow for linting

on:
  workflow_call:
    inputs:
      lint_dir:
        description: "Path to the directory to lint"
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Rye
        uses: baptiste0928/cargo-install@v3
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main
      - name: Install dependencies
        run: |
          rye sync
      - name: Lint with ruff
        run: |
          rye run ruff ${{ inputs.lint_dir }}
      - name: Lint with mypy
        run: |
          rye run mypy ${{ inputs.lint_dir }}
