name: Reusable workflow for unit tests

on:
  workflow_call:
    inputs:
      package_dir:
        description: "Path to the package directory containing the module to be tested"
        required: true
        type: string
      test_dir:
        description: "Path to the test directory"
        required: true
        type: string

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Rye
        uses: baptiste0928/cargo-install@v3
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main
      - name: Install dependencies
        run: |
          rye sync
      - name: Run unit tests
        env:
          ENV: ${{(github.ref == 'refs/heads/main' && 'prod') || 'dev'}}
          CI: true
        run: |
          rye run pytest -v --cov=${{ inputs.package_dir }} --cov-report=term-missing ${{ inputs.test_dir }}
